### ISSUE TITLE
switching to state _state_default GameKill raised a exception

### ISSUE THREAD

**Issue by ykws** [ykws/IkaLog#2]
```
Splatted an enemy! (2 streak)
<ikalog.scenes.game.special_weapon.GameSpecialWeapon object at 0x10c0a9518>: switching to state _state_default
GameKill raised a exception >>>>
Traceback (most recent call last):
  File "/Users/ykws/Workspace/IkaLog/ikalog/engine.py", line 275, in process_scene
    scene.match(context)
  File "/Users/ykws/Workspace/IkaLog/ikalog/scenes/scene.py", line 111, in match
    self._matched = self.match_no_cache(context)
  File "/Users/ykws/Workspace/IkaLog/ikalog/scenes/game/kill.py", line 125, in match_no_cache
    current_kills = self.find_kill_messages(context)
  File "/Users/ykws/Workspace/IkaLog/ikalog/scenes/game/kill.py", line 75, in find_kill_messages
    img_name_left = np.min(img_name_x_hist)
  File "/usr/local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 2350, in amin
    out=out, keepdims=keepdims)
  File "/usr/local/lib/python3.5/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

<<<<<
```

**Comment by ykws** [comment]
Not reproduce.
